Description: Instancia EC2 para Sistema Web

Resources:
  # Security Group 
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22 and 80 and 443
      VpcId: !ImportValue 'VpcId'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: "0.0.0.0/0"
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: "0.0.0.0/0"
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: "0.0.0.0/0"               

  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-0c7217cdde317cfec"
      Tags:
        - Key: Name
          Value: WebServer1
      KeyName: "shdmkey2"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: 30
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !GetAtt "InstanceSecurityGroup.GroupId"
          SubnetId: !ImportValue "PubSN2Id"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            apt-get update
            apt-get -y install curl
            apt-get -y install jq
            apt-get -y install mc
            apt-get -y install net-tools
  EIP:
      Type: AWS::EC2::EIP
      Properties:
        InstanceId: !Ref EC2Instance
        Domain: !ImportValue 'VpcId'
        Tags:
          - Key: Name
            Value: Web1EIP
Outputs:
  PublicWebIP:
  #  Description: Public IP da instancia EC2 Web Server
    Value: !GetAtt [EC2Instance, Web1EIP]
    Export:
        Name: PublicWebIP
  SGBCId:
    Description: Id do SG da instancia EC2
    Value: !GetAtt "InstanceSecurityGroup.GroupId"
    Export:
        Name: SGWebId     