Description: Gateway Endpoint para as Camadas de Usuarios e Nevo

Resources:
  S3GatewayEndpointUsers:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Gateway'
      VpcId: 'vpc-09a457505caf38242'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
            Resource: 
              - "arn:aws:s3:::repo-users-dicom-sa-east-1-730335447253/*"
      RouteTableIds:
        - 'rtb-0ca946022ab009bda'
          
  S3GatewayEndpointFog:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Gateway'
      VpcId: !ImportValue VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:GetObject'
            Resource: 
              - "arn:aws:s3:::repo-fog-dicom-sa-east-1-730335447253/*"
      RouteTableIds:
        - !ImportValue rtPubId