Description: Bucket S3 para depósito de Imagens/Arquivos (ex. Imagens Dicom) da Camada Fog

Resources:
  S3BucketFog:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'repo-fog-dicom-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: 'arn:aws:kms:sa-east-1:730335447253:key/ae70bafe-e90a-4612-a43e-40f9f34cbce5'

Outputs:
  BucketNameFog: 
    Description: Nome do Bucket da Camada em Nevoa para Deposito de Imagens
    Value: !Ref S3BucketFog   
    Export: 
      Name: BucketNameFog