Description: Instancia EC2 para gerenciar BC Hyperledger Fabric - Amazon Linux

Resources:
  # Security Group 
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22 and 80 and AllPortsTCP
      VpcId: !ImportValue 'VpcId'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: "0.0.0.0/0"
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: "0.0.0.0/0"
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: "0.0.0.0/0"        
      - IpProtocol: tcp
        FromPort: 7051
        ToPort: 7051
        CidrIp: "0.0.0.0/0"   
      - IpProtocol: tcp
        FromPort: 9051
        ToPort: 9051
        CidrIp: "0.0.0.0/0"           
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: "0.0.0.0/0"

  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-02c21308fed24a8ab"
      Tags:
        - Key: Name
          Value: BCHost1
      KeyName: "shdm2key"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sda1"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: 30
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !GetAtt "InstanceSecurityGroup.GroupId"
          SubnetId: !ImportValue "PrivSN1Id"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            apt-get update
            apt-get -y install curl
            apt-get -y install docker-compose
            apt-get -y install docker
            apt-get -y install jq
            apt-get -y install mc
            apt-get -y install telnet
            apt-get -y install emacs
  EIP:
      Type: AWS::EC2::EIP
      Properties:
        InstanceId: !Ref EC2Instance
        Domain: !ImportValue 'VpcId'
        Tags:
          - Key: Name
            Value: BC1EIP
Outputs:
  PublicBCIP:
    Description: Public IP da instancia EC2 BC
    Value: !GetAtt [EC2Instance, PublicIp]
    Export:
        Name: PublicBCIP
  SGBCId:
    Description: Id do SG da instancia EC2
    Value: !GetAtt "InstanceSecurityGroup.GroupId"
    Export:
        Name: SGBCId     