Description: Instancia Cloud9 para Desenvolvimento (sa-east-1)

Resources:
  Cloud9:
    Type: 'AWS::Cloud9::EnvironmentEC2'
    Properties:
      AutomaticStopTimeMinutes: 30
      InstanceType: "t2.small"
      ImageId: "ubuntu-22.04-x86_64"
      Name: "AmbienteCloud9"
      SubnetId: !ImportValue PubSN1Id