Description: Rotas us-east-1 - para o VPC Peering Connection - Cloud to Fog

Resources:
  Rota1:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !ImportValue 'rtPubId'
      DestinationCidrBlock: 10.10.0.0/16
      VpcPeeringConnectionId: 'pcx-0f264775da1f59fcf'

  Rota2:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !ImportValue 'rtPriv1Id'
      DestinationCidrBlock: 10.10.0.0/16
      VpcPeeringConnectionId: 'pcx-0f264775da1f59fcf'

  Rota3:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !ImportValue 'rtPriv2Id'
      DestinationCidrBlock: 10.10.0.0/16
      VpcPeeringConnectionId: 'pcx-0f264775da1f59fcf'

  Rota4:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !ImportValue 'rtPriv3Id'
      DestinationCidrBlock: 10.10.0.0/16
      VpcPeeringConnectionId: 'pcx-0f264775da1f59fcf' 
           