Description: Buckets S3 para depositos na Camada Fog

Resources:
  S3BucketFog:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'repo-fog-dicom-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: 'arn:aws:kms:sa-east-1:904233115303:key/b5a7d4e5-185a-47d2-b53a-e8f43535da2a'
Outputs:
  BucketNameFog: 
    Description: Nome do Bucket da Camada em Nevoa para Deposito de Imagens
    Value: !Ref S3BucketFog   
    Export: 
      Name: BucketNameFog  