Description: Gateway Endpoint para as Camadas de Usuarios e Nevoa

Resources:
  S3GatewayEndpointUsers:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Gateway'
      #id da vpc padrao 172.31.0.0/16
      VpcId: 'vpc-0dc525f431142fe3f'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource: 
              - "*"
      RouteTableIds:
      #id da tabela de rotas da vpc 172.31.0.0/16
        - 'rtb-0be6d947e07ba8e72'      

  S3GatewayEndpointUsers2:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Gateway'
      VpcId: !ImportValue VpcUId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource: 
              - "*"
      RouteTableIds:
        - !ImportValue rtPrivUId

  S3GatewayEndpointFog:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Gateway'
      VpcId: !ImportValue VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource: 
              - "*"
      RouteTableIds:
        - !ImportValue rtPrivId
 
  SecretsManagerGatewayEndpointFog:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Interface'
      VpcId: !ImportValue VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 'secretsmanager:*'
            Resource: 
              - "*"

  KmsGatewayEndpointUsers:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Interface'
      #id da vpc padrao 172.31.0.0/16
      VpcId: 'vpc-0dc525f431142fe3f'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.kms'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 'kms:GenerateDataKey'
            Resource: 
              - "*"     

  KmsGatewayEndpointFog:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Interface'
      VpcId: !ImportValue VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.kms'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 'kms:GenerateDataKey'
              - 'kafka:ListScramSecrets'
            Resource: 
              - "*"                   

  EventsGatewayEndpointFog:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Interface'
      VpcId: !ImportValue VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.events'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 'events:*'
              - 'pipes:*'
            Resource: 
              - "*"                    
  
  StsGatewayEndpointFog:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Interface'
      VpcId: !ImportValue VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.sts'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - '*'
            Resource: 
              - "*"                  
  LambdaGatewayEndpointFog:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcEndpointType: 'Interface'
      VpcId: !ImportValue VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.lambda'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - '*'
            Resource: 
              - "*"