Description: VPC Peering Connection - Conexao entre Camadas de Usuarios, Nevoa e Nuvem

Resources:
  #VPC Peering
  vpcPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !ImportValue 'VpcId'
      #VPC de Destino (alterar o PeerVpcId)
      PeerRegion: us-east-1
      PeerVpcId: vpc-02aebcb211cc50612
      Tags:
      - Key: Name
        Value: VPC-Peering-Fog-to-Cloud
  vpcPeeringConnection2:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !ImportValue 'VpcUId'
      #VPC de Destino (alterar o PeerVpcId)
      PeerRegion: sa-east-1
      PeerVpcId: vpc-0ed8ce9ac668693b8
      Tags:
      - Key: Name
        Value: VPC-Peering-Users-to-Fog
  vpcPeeringConnection3:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: vpc-0dc525f431142fe3f
      PeerRegion: sa-east-1
      PeerVpcId: vpc-0ed8ce9ac668693b8
      Tags:
      - Key: Name
        Value: VPC-Peering-Users2-to-Fog
#Outputs
Outputs:
  VpcPeeringId:
    Description: ID of created VPC Peering Fog-to-Cloud
    Value: !Ref vpcPeeringConnection
    Export:
      Name: VpcPeeringId
  VpcPeeringId2:
    Description: ID of created VPC Peering Users-to-Fog
    Value: !Ref vpcPeeringConnection2
    Export:
      Name: VpcPeeringId2 
  VpcPeeringId3:
    Description: ID of created VPC Peering Users2-to-Fog
    Value: !Ref vpcPeeringConnection3
    Export:
      Name: VpcPeeringId3       