Description: Bucket S3 para depósito de Imagens/Arquivos (ex. Imagens Dicom)

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub 'repo-users-dicom-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              #Alterar KMS-KEY-ARN abaixo
              KMSMasterKeyID: arn:aws:kms:sa-east-1:904233115303:key/bf71493e-1ce8-4939-b1f8-bc64b7f5c5cd

Outputs:
  BucketName: 
    Description: Nome do Bucket da Camada de Usuarios para Deposito de Imagens
    Value: !Ref S3Bucket   
    Export: 
      Name: BucketName