spring:
  datasource:
    url: 'jdbc:postgresql://hapifhir.cqmgcztxfm18.us-east-1.rds.amazonaws.com:5432/dbhapifhir'
    username: hapifhir
    password: hapifhirpass
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false
~                                     
