apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hapifhir
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hapifhir
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
