apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: hapifhir
  name: hapifhir
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: hapifhir
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: hapifhir
    spec:
      containers:
        - image: hapiproject/hapi:latest
          name: container-hapifhir
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /app/config/application.yaml
              name: hapi
              subPath: application.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: application.yaml
                path: application.yaml
            name: hapi
          name: hapi
status: {}
